import fs from 'fs/promises';
import path from 'path';
import { GraphView } from '@/components/GraphView';
import Link from 'next/link';
import { SearchView } from '@/components/SearchView';

export default async function GlobalGraphPage() {
    // Read the global graph data generated by sparks builder
    const graphPath = path.join(process.cwd(), 'public', 'api', 'notes', `graph.json`);

    let graphData = { nodes: [], edges: [] };
    try {
        const data = await fs.readFile(graphPath, 'utf-8');
        graphData = JSON.parse(data);
    } catch (error) {
        console.error("No global graph data found", error);
    }

    return (
        <div className="min-h-screen bg-zinc-50 dark:bg-black font-sans py-16 px-6 md:px-12 lg:px-24 flex justify-center gap-16">

            <main className="w-full max-w-[1000px] flex flex-col shrink-[4]">
                {/* Navigation Breadcrumb / Back Link */}
                <nav className="mb-8 text-sm font-medium flex justify-between items-center">
                    <Link href="/notes" className="text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100 flex items-center gap-2 transition-colors w-fit">
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                        </svg>
                        Back to notes
                    </Link>
                </nav>

                <header className="mb-6 pb-4 border-b border-zinc-200 dark:border-zinc-800">
                    <h1 className="text-4xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-50 leading-tight">
                        Global Graph
                    </h1>
                    <p className="mt-2 text-zinc-500 text-sm">
                        A bird's eye view of the entire knowledge network. Drag to pan and scroll to zoom.
                    </p>
                </header>

                {graphData.nodes.length > 0 ? (
                    <GraphView data={graphData} global={true} />
                ) : (
                    <div className="py-20 text-center text-zinc-500">
                        No graph data found. Re-run the sparks builder.
                    </div>
                )}
            </main>

            {/* Right Sidebar */}
            <aside className="w-[300px] shrink-0 sticky top-16 h-[calc(100vh-8rem)] hidden xl:flex flex-col gap-10 overflow-y-auto pb-10 custom-scrollbar pr-4">
                <SearchView />
            </aside>
        </div>
    );
}
