import { visit } from 'unist-util-visit';
import type { Element } from 'hast';
import type { FullStackPlugin, PluginConfig } from '../core/types';

/**
 * Transforms standard markdown checkboxes into <sparks-checkbox> elements
 * which can be intercepted by the frontend for interactive functionality.
 */
function rehypeCheckbox() {
    return (tree: any) => {
        visit(tree, 'element', (node: Element) => {
            if (
                node.tagName === 'input' &&
                node.properties &&
                node.properties.type === 'checkbox'
            ) {
                // Change the element name to <sparks-checkbox>
                node.tagName = 'sparks-checkbox';
                // Keep the original properties (like checked=true)
            }
        });
    };
}

/**
 * Interactive Task Lists
 * Intercepts default disabled checkboxes generated by remark-gfm
 * and prepares them for the frontend to replace with interactive UI.
 */
export const CheckboxPlugin = (): FullStackPlugin => {
    return {
        name: 'interactive-checkbox',
        description: 'Converts disabled markdown task lists into interactive components',
        rehypePlugins: [
            { plugin: rehypeCheckbox } as PluginConfig,
        ],
    };
};
